"""Questions hardcodées pour le fallback Word/Excel (quand pas de template PDF)"""

def _get_inventaire_questions():
    return {
        "q1_1_instructions_ecrites": "Existe-t-il des instructions écrites ?",
        "q1_2_lieux_types_couverts": "Tous les lieux de stockage et tous les types de stocks sont-ils couverts ?",
        "q1_3_stocks_entreprise": "Stocks appartenant à l'entreprise ?",
        "q1_4_stocks_tiers": "Stocks détenus par des tiers ?",
        "q1_5_rangement_prealable": "Le rangement préalable permet-il d'effectuer les comptages avec facilité ?",
        "q1_6_identification_stocks": "L'identification des stocks est-elle faite ?",
        "q1_7_comptages_aveugle": "Les comptages se font-ils en aveugle (sans la connaissance des quantités théoriques) ?",
        "q1_8_double_comptage_ecarts": "En cas de double comptage, les écarts sont-ils analysés ?",
        "q1_9_stocks_identifies": "Les stocks comptés sont-ils clairement identifiés ?",
        "q1_10_ecarts_inventaire_permanent": "S'il existe un inventaire permanent, les écarts sont-ils analysés ?",
        "q2_1_personne_independante": "Y a-t-il au moins une personne indépendante du service Magasin dans les équipes de comptage ?",
        "q2_2_instructions_equipes": "Les équipes de comptage ont-elles reçu des instructions précises ?",
        "q2_3_connaissances_techniques": "Y a-t-il au moins une personne avec les connaissances techniques suffisantes ?",
        "q3_1_techniques_comptage": "Les techniques de comptage sont-elles bien définies ?",
        "q3_2_probleme_tare": "A-t-on bien appréhendé le problème de la tare ?",
        "q3_3_verification_qualite": "Y a-t-il vérification de la qualité des articles ?",
        "q3_4_stocks_deprecier": "Les stocks à déprécier sont-ils correctement recensés ?",
        "q4_1_mouvements_periode": "Y a-t-il des mouvements d'articles pendant la période de prise d'inventaire ?",
        "q4_2_mesures_doubles_comptages": "Des mesures ont-elles été prises pour éviter les doubles comptages ?",
        "q4_3_bons_entree_sortie": "Les entrées et les sorties se font-elles au vu des bons ?",
        "q4_4_releve_numero_bons": "Relevé des numéros de bons ?",
        "q4_5_determination_propriete": "Détermination de la propriété ?",
        "q4_6_livraisons_fournisseurs": "Y a-t-il eu des livraisons des fournisseurs pendant l'inventaire ?",
        "q4_7_identification_livraisons": "Identification des livraisons ?",
        "q4_8_expeditions_clients": "Y a-t-il eu des expéditions de marchandises aux clients pendant l'inventaire ?",
        "q4_9_identification_expeditions": "Identification des expéditions ?",
        "q4_10_consignation": "Comment a-t-on traité les articles en consignation ?",
        "q4_11_marchandises_tiers": "Marchandises détenues par des tiers ?",
        "q4_12_demandes_confirmation": "A-t-on fait des demandes de confirmation ?",
        "q4_13_rapprochement_bons": "Rapprochement bons/inventaire permanent ?",
        "q5_1_comptages_comparés": "Les comptages sont-ils comparés avec l'inventaire permanent par des personnes différentes ?",
        "q5_2_raisons_ecarts": "Raisons des écarts ?",
        "q5_3_enquete_prealable": "Une enquête est-elle effectuée préalablement à toute correction ?",
        "q5_4_liste_ecarts_direction": "La liste des écarts est-elle communiquée à la direction ?",
    }

def _get_evenement_questions():
    return {
        "q1_0_pv_conseil": "A-t-on examiné les registres des PV de conseils d'administration jusqu'à la date du rapport ?",
        "q1_1_assemblees_sans_pv": "S'est-on informé auprès de la direction pour savoir si des assemblées ont été réunis sans PV ?",
        "q1_2_copie_pv": "A-t-on obtenu une copie du projet de procès verbal ?",
        "q1_3_comites_direction": "La même démarche a-t-elle été suivie pour les comités de direction ?",
        "q1_4_situations_intermediaires": "L'entreprise a-t-elle établi des situations intermédiaires post-clôture ?",
        "q1_5_principes_comptables_identiques": "Sont-elles établies selon les mêmes principes comptables ?",
        "q1_6_comparaison_cloture": "A-t-on comparé avec les comptes annuels de clôture ?",
        "q1_7_comparaison_budget": "A-t-on comparé avec le budget ?",
        "q1_8_modifications_ventes": "Modifications significatives des ventes ?",
        "q1_8b_modifications_charges": "Modifications significatives des charges ?",
        "q1_8c_modifications_marge": "Modifications significatives de la marge brute ?",
        "q1_9_pertes_exceptionnelles": "Pertes et profits exceptionnels ?",
        "q1_10_modifications_capital": "Modifications du capital ?",
        "q1_10b_reserves": "Modifications des réserves ?",
        "q1_10c_dettes_long_terme": "Modifications des dettes à long terme ?",
        "q1_11_fonds_roulement": "Modification significative du fonds de roulement ?",
        "q1_12_passifs_eventuels": "Passifs éventuels devenus certains ?",
        "q1_13_proces_litiges": "Procès ou litiges nés après clôture ?",
        "q1_14_controles_fiscaux": "Contrôles fiscaux après clôture ?",
        "q1_15_immobilisations_acquisitions": "Modifications significatives des immobilisations (acquisitions/cessions) ?",
        "q1_15b_disparition_obsolescence": "Disparition ou obsolescence ?",
        "q1_16_prises_participation": "Prises de participation significatives ?",
        "q1_17_moins_value": "Moins-value sur cession d'immobilisations ?",
        "q1_18_surestimation": "Résulte-t-elle d'une surestimation ?",
        "q1_18b_circonstances_post_cloture": "De circonstances post-clôture ?",
        "q1_19_pertes_stock": "Pertes non provisionnées sur stock ?",
        "q1_19b_pertes_creances": "Pertes non provisionnées sur créances ?",
        "q1_20_augmentation_stock": "Augmentation anormale des stocks ?",
        "q1_20b_augmentation_creances": "Augmentation anormale des créances ?",
        "q1_21_comparaisons_sans_situations": "Comparaisons effectuées sans situations intermédiaires ?",
        "q1_22_interrogation_dirigeants_diff": "Interrogation des dirigeants sur les différences ?",
        "q1_23_autres_evenements": "Autres événements significatifs ?",
        "q1_24_conflits_sociaux": "Conflits sociaux ?",
        "q1_24b_pertes_clients": "Pertes de clients importants ?",
        "q1_24c_modifications_approvisionnement": "Modifications des sources d'approvisionnement ?",
        "q1_24d_changements_production": "Changements dans le processus de production ?",
        "q1_25_lettre_confirmation": "Lettre de confirmation obtenue ?",
        "q2_1_renseignements_complementaires": "Événements fournissant des renseignements complémentaires ?",
        "q2_2_modification_comptes": "Comptes annuels modifiés ?",
        "q2_3_reserve_rapport": "Réserve appropriée dans le rapport ?",
        "q2_4_continuite_exploitation": "Continuité d'exploitation affectée ?",
        "q2_5_situation_non_existante": "Situation qui n'existait pas à la date du bilan ?",
        "q2_6_continuite_affectee": "Continuité affectée par ces événements ?",
        "q2_7_description_evenements": "Événements correctement décrits dans les notes ?",
        "q2_8_mention_rapport": "Tenu compte dans la rédaction du rapport ?",
        "q2_9_mention_appropriee": "Mention appropriée dans le rapport ?",
    }

def _get_fin_questions():
    return {
        "q1_1_mise_a_jour": "Mise à jour des éléments du dossier ?",
        "q1_2_examen_analytique": "Examen analytique global ?",
        "q1_3_identification_risques": "Identification des risques ?",
        "q1_4_plan_mission": "Plan de mission ?",
        "q1_5_lettre_mission": "Lettre de mission ?",
    }

def _get_verification_questions():
    return {}  # À compléter selon besoin

def _get_pri_questions():
    return {}  # À compléter selon besoin